### ISSUE TITLE
[RFE] Allow kustomize --enable-helm equivalent functionality

### ISSUE THREAD

**Issue by eformat** [open-cluster-management-io/policy-generator-plugin#105]
This may not be feasible due to the way YAML is parsed by the plugin, but it would be great if the plugin could work "as if" you had called:

kustomize build --enable-alpha-plugins --enable-helm ./

this would allow [kustomization of a helm chart](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md) functionality with PolicyGenerator.

of course, some may also consider this undesireable as well - but i thought it was worth asking !

**Comment by dhaiducek** [comment]
Hi @eformat! Thanks for opening an issue! Would you please elaborate a bit more on this use-case? Are you requesting that, as part of providing a Kustomization manifest as an input, that plugins and Helm are enabled there as well?

**Comment by eformat** [comment]
hi @dhaiducek - yes exactly so - use Policy Generator -> kustomize manifests -> to call helm charts 
my example use case is using PolicyGenerator to bootstrap Team Based ArgoCD's

https://github.com/eformat/acm-gitops-helm

but because   " --enable-helm" does not get passed on via PolicyGenrator .. i have two step the process for now.
make sense ?

**Comment by dhaiducek** [comment]
@eformat I'll take this up with others on our team. I don't think we'd want it turned on by default, but I don't see why we couldn't raise a flag in the generator to pass to our Kustomize instance.

**Comment by dhaiducek** [comment]
I've just entered a PR for our team to review. It lacks tests (though it works locally)--does this look like it'd meet requirements for your use case?
- https://github.com/open-cluster-management-io/policy-generator-plugin/pull/109

**Comment by eformat** [comment]
@dhaiducek - yes it does. i just built your branch and tried it out on my repo. enabling this in the policy generator manifest:

```yaml
    manifests:
      - path: helm-input/
        kustomizeOptions:
          enableAlphaPlugins: true
          enableHelm: true
```

worked like a charm ! and then ```enableHelm: false``` correctly gives the error

```
`: must specify --enable-helm
Error: failure in plugin configured via /tmp/kust-plugin-config-3212683469; exit status 1: exit status 1
```

thanks & great stuff 🎉

**Comment by dhaiducek** [comment]
@eformat You probably noticed, but we opted for an env, `POLICY_GEN_ENABLE_HELM="true"` to enable Helm globally rather than per-generator. Thanks for raising this, and apologies for the rather slow resolution!

**Comment by eformat** [comment]
thanks @dhaiducek ! yes , all good - i will be able to stop carrying the patch now for this ! thanks a lot i use it all the time :)
