### ISSUE TITLE
RFE: Add version information 

### ISSUE THREAD

**Issue by gnunn1** [open-cluster-management-io/policy-generator-plugin#118]
I have the opensource policygenerator on my system but running into an incompatibility with v2.7 of the ACM version. There doesn't seem to be any way to get it to output it's version?

**Comment by dhaiducek** [comment]
Thanks for the RFE, @gnunn1! Indeed we don't currently have version information embedded, so this would be a great addition!

**Comment by dhaiducek** [comment]
@gnunn1 I've implemented a `--version` flag for the binary but the way it's pulled into the subscription container won't work. I'll need to follow it up with an additional PR.

**Comment by dhaiducek** [comment]
Sorry for the noise--on further investigation the implementation will work, with some adjustments to the AppSub generator build.

**Comment by dhaiducek** [comment]
The build adjustments have been made! The one lingering issue is that using `go install` doesn't properly return a versioned binary (which seems to be a known issue for Go binaries), but downloading the binary from a release here or using `make build-binary` will return a versioned binary and the binary in the AppSub container is versioned.

**Comment by gnunn1** [comment]
Thanks for your work on this Dale!
