### ISSUE TITLE
Allow to set remediationAction for policies with Gatekeeper Constraints and templates

### ISSUE THREAD

**Issue by jwennerberg** [open-cluster-management-io/policy-generator-plugin#155]
When generating policies from Gatekeeper manifests (Constraint/ConstraintTemplate) no `remediationAction` is set for the root policy, even when specified in the PolicyGenerator manifest.

Without this remediation (enforcementAction) have to be controlled for each constraint. It would be nice set or override this with PolicyGenerator instead.

**Comment by dhaiducek** [comment]
Resolved in:
- https://github.com/open-cluster-management-io/policy-generator-plugin/pull/167
